#!/bin/sh

# Copyright (C) 2020 Dawid Kujawa <dawid.kujawa@dynfi.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# PROVIDE: dfconag

. /etc/rc.subr

name=dfconag
rcvar=${name}_enable
start_precmd=${name}_prestart
start_cmd=${name}_start
stop_cmd=${name}_stop
extra_commands=status
status_cmd=${name}_status

load_rc_config ${name}

dfconag_prestart()
{
}

dfconag_start()
{
    if ! pgrep -qF /var/run/dfconag.pid 2> /dev/null; then
        echo "Starting DFConAg autossh to ${dfm_host}"
        configctl template reload OPNsense/DFConAg
        env AUTOSSH_GATETIME=0 env AUTOSSH_PIDFILE=/var/run/dfconag.pid env AUTOSSH_LOGFILE=/var/log/dfconag.log env AUTOSSH_LOGLEVEL=6 env AUTOSSH_PATH=/usr/local/bin/ssh /usr/local/bin/autossh -M 0 -f -N -oUserKnownHostsFile=/var/dfconag/known_hosts -oServerAliveInterval=30 -oServerAliveCountMax=3 -i /var/dfconag/key -p ${dfm_ssh_port} -R ${main_tunnel_port}:localhost:${remote_ssh_port} -R ${dv_tunnel_port}:localhost:${remote_dv_port} robot@${dfm_host}
    else
        echo "already running"
    fi
}

dfconag_stop()
{
    if [ -f /var/run/dfconag.pid ]; then
        echo "Stopping DFConAg autossh"
        /bin/pkill -TERM -F /var/run/dfconag.pid
        if [ -f /var/run/dfconag.pid ]; then
            rm /var/run/dfconag.pid
        fi
        configctl template reload OPNsense/DFConAg
    fi
}

dfconag_status() {
    if pgrep -qF /var/run/dfconag.pid 2> /dev/null; then
        echo "dfconag is running"
    else
        echo "dfconag is not running"
    fi
}

run_rc_command $1
