<?php

/*
 * Copyright (C) 2015-2020 Deciso B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/* Language support, autogenerated file */
echo gettext('AJAX: Get Service Providers');
echo gettext('AJAX: Get Stats');
echo gettext('All pages');
echo gettext('Dashboard (all)');
echo gettext('Dashboard (widgets only)');
echo gettext('Diagnostics: ARP Table');
echo gettext('Diagnostics: Authentication');
echo gettext('Diagnostics: Backup / Restore');
echo gettext('Diagnostics: Configuration History');
echo gettext('Diagnostics: Factory defaults');
echo gettext('Diagnostics: Halt system');
echo gettext('Diagnostics: Logs: DHCP');
echo gettext('Diagnostics: Logs: Firewall: Live View');
echo gettext('Diagnostics: Logs: Firewall: Plain View');
echo gettext('Diagnostics: Logs: Firewall: Summary View');
echo gettext('Diagnostics: Logs: Gateways');
echo gettext('Diagnostics: Logs: Settings');
echo gettext('Diagnostics: Logs: System');
echo gettext('Diagnostics: NDP Table');
echo gettext('Diagnostics: Netflow configuration');
echo gettext('Diagnostics: Netstat');
echo gettext('Diagnostics: Network Insight');
echo gettext('Diagnostics: PF Table IP addresses');
echo gettext('Diagnostics: Packet Capture');
echo gettext('Diagnostics: Ping');
echo gettext('Diagnostics: Reboot System');
echo gettext('Diagnostics: Reset state');
echo gettext('Diagnostics: Routing tables');
echo gettext('Diagnostics: Shaper status');
echo gettext('Diagnostics: Show States');
echo gettext('Diagnostics: States Summary');
echo gettext('Diagnostics: System Activity');
echo gettext('Diagnostics: System Health');
echo gettext('Diagnostics: Test Port');
echo gettext('Diagnostics: Traceroute');
echo gettext('Diagnostics: pfInfo');
echo gettext('Diagnostics: pfTop');
echo gettext('DynFi Connection Agent');
echo gettext('Firewall: Alias: Edit');
echo gettext('Firewall: Aliases');
echo gettext('Firewall: NAT: 1:1');
echo gettext('Firewall: NAT: 1:1: Edit');
echo gettext('Firewall: NAT: NPT');
echo gettext('Firewall: NAT: NPT: Edit');
echo gettext('Firewall: NAT: Outbound');
echo gettext('Firewall: NAT: Outbound: Edit');
echo gettext('Firewall: NAT: Port Forward');
echo gettext('Firewall: NAT: Port Forward: Edit');
echo gettext('Firewall: Normalization');
echo gettext('Firewall: Rules');
echo gettext('Firewall: Rules: API');
echo gettext('Firewall: Rules: Edit');
echo gettext('Firewall: Schedules');
echo gettext('Firewall: Schedules: Edit');
echo gettext('Firewall: Shaper');
echo gettext('Firewall: SourceNat: API');
echo gettext('Firewall: Virtual IP Address: Edit');
echo gettext('Firewall: Virtual IP Addresses');
echo gettext('Interfaces: Assign network ports');
echo gettext('Interfaces: Bridge');
echo gettext('Interfaces: Bridge edit');
echo gettext('Interfaces: GIF');
echo gettext('Interfaces: GIF: Edit');
echo gettext('Interfaces: GRE');
echo gettext('Interfaces: GRE: Edit');
echo gettext('Interfaces: Groups');
echo gettext('Interfaces: Groups: Edit');
echo gettext('Interfaces: LAGG');
echo gettext('Interfaces: LAGG: Edit');
echo gettext('Interfaces: Loopback');
echo gettext('Interfaces: PPPs');
echo gettext('Interfaces: PPPs: Edit');
echo gettext('Interfaces: VLAN');
echo gettext('Interfaces: VLAN: Edit');
echo gettext('Interfaces: VXLAN');
echo gettext('Interfaces: WAN');
echo gettext('Interfaces: Wireless');
echo gettext('Interfaces: Wireless edit');
echo gettext('Lobby: Login / Logout / Dashboard');
echo gettext('Services: C-ICAP');
echo gettext('Services: Captive Portal');
echo gettext('Services: ClamAV');
echo gettext('Services: DHCP Relay');
echo gettext('Services: DHCP Server: Edit static mapping');
echo gettext('Services: DHCP server');
echo gettext('Services: DHCPv6 Relay');
echo gettext('Services: DHCPv6 Server: Edit static mapping');
echo gettext('Services: DHCPv6 server');
echo gettext('Services: DNS Filter');
echo gettext('Services: Dnsmasq DNS: Edit Domain Override');
echo gettext('Services: Dnsmasq DNS: Edit Host');
echo gettext('Services: Dnsmasq DNS: Log File');
echo gettext('Services: Dnsmasq DNS: Settings');
echo gettext('Services: Intrusion Detection');
echo gettext('Services: NTP');
echo gettext('Services: Proxy');
echo gettext('Services: Router advertisements');
echo gettext('Services: SMART');
echo gettext('Services: Unbound (mvc)');
echo gettext('Services: Unbound DNS: Access Lists');
echo gettext('Services: Unbound DNS: Advanced');
echo gettext('Services: Unbound DNS: Edit Domain Override');
echo gettext('Services: Unbound DNS: Edit Host Override');
echo gettext('Services: Unbound DNS: General');
echo gettext('Services: Unbound DNS: Log File');
echo gettext('Status: CARP');
echo gettext('Status: DHCP leases');
echo gettext('Status: DHCPv6 leases');
echo gettext('Status: HA backup');
echo gettext('Status: IPsec');
echo gettext('Status: IPsec: Leasespage');
echo gettext('Status: IPsec: SAD');
echo gettext('Status: IPsec: SPD');
echo gettext('Status: Interfaces');
echo gettext('Status: NTP');
echo gettext('Status: NTP GPS');
echo gettext('Status: NTP PPS');
echo gettext('Status: OpenVPN');
echo gettext('Status: Services');
echo gettext('Status: System logs: Captive portal');
echo gettext('Status: System logs: IPsec VPN');
echo gettext('Status: System logs: NTP');
echo gettext('Status: System logs: OpenVPN');
echo gettext('Status: System logs: PPP');
echo gettext('Status: System logs: Routing');
echo gettext('Status: System logs: Wireless');
echo gettext('Status: Traffic Graph');
echo gettext('Status: Wireless');
echo gettext('System Setup Wizard');
echo gettext('System: Advanced: Admin Access Page');
echo gettext('System: Advanced: Firewall and NAT');
echo gettext('System: Advanced: Miscellaneous');
echo gettext('System: Advanced: Network');
echo gettext('System: Advanced: Tunables');
echo gettext('System: Authentication Servers');
echo gettext('System: CA Manager');
echo gettext('System: CRL Manager');
echo gettext('System: Certificate Manager');
echo gettext('System: Crash Reporter');
echo gettext('System: Deny config write');
echo gettext('System: Firmware');
echo gettext('System: Gateway Groups');
echo gettext('System: Gateways');
echo gettext('System: Gateways: Edit Gateway');
echo gettext('System: Gateways: Edit Gateway Groups');
echo gettext('System: General Setup');
echo gettext('System: Group Manager: Add Privileges');
echo gettext('System: Group manager');
echo gettext('System: High Availability');
echo gettext('System: License');
echo gettext('System: Settings: Cron');
echo gettext('System: Static Routes');
echo gettext('System: User Manager');
echo gettext('System: User Manager: Add Privileges');
echo gettext('System: User Password Manager');
echo gettext('VPN: IPsec');
echo gettext('VPN: IPsec: Edit Phase 1');
echo gettext('VPN: IPsec: Edit Phase 2');
echo gettext('VPN: IPsec: Edit Pre-Shared Keys');
echo gettext('VPN: IPsec: Key Pairs');
echo gettext('VPN: IPsec: Mobile');
echo gettext('VPN: IPsec: Pre-Shared Keys List');
echo gettext('VPN: OpenVPN: Client');
echo gettext('VPN: OpenVPN: Client Export Utility');
echo gettext('VPN: OpenVPN: Client Specific Override');
echo gettext('VPN: OpenVPN: Server');
echo gettext('VPN: Zerotier');
echo gettext('WebCfg - Services: Monit System Monitoring page');
echo gettext('XMLRPC Library');
echo gettext('redis');
