<?php

/*
 * Copyright (C) 2015-2022 Deciso B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/* Language support, autogenerated file */
echo gettext('None');
echo gettext('
                    Controls which objects to keep in the memory cache (cache_mem)
                    always:	Keep most recently fetched objects in memory (default)
                    disk: Only disk cache hits are kept in memory, which means an object must first be cached on disk and then hit a second time before cached in memory.
                    network: Only objects fetched from network is kept in memory
                ');
echo gettext('
                  The proxy error pages can be altered, default layout uses OPNsense content, when Squid is selected
                  the content for the selected language will be used (standard squid layout), Custom offers the possibility
                  to upload your own theme content.
                ');
echo gettext('
            Configure a maximum Time to live in seconds for RRsets and messages in the cache.
            When the internal TTL expires the cache item is expired.
            This can be configured to force the resolver to query for data more often and
            not trust (very large) TTL values.
        ');
echo gettext('
            Configure a minimum Time to live in seconds for RRsets and messages in the cache.
            If the minimum value kicks in, the data is cached for longer than
            the domain owner intended, and thus fewer queries are made to look up the data.
            The 0 value ensures the data in the cache is as the domain owner intended.
            High values can lead to trouble as the data in the cache might not match up with the actual data anymore.
        ');
echo gettext('
            DNSKEYs are fetched earlier in the validation process when a Delegation signer is encountered.
            This helps lower the latency of requests but does utilize a little more CPU.
        ');
echo gettext('
            DNSSEC data is required for trust-anchored zones. If such data is absent, the zone becomes bogus.
            If this is disabled and no DNSSEC data is received, then the zone is made insecure.
        ');
echo gettext('
            Destination ip address for entries in the blocklist (leave empty to use default: 0.0.0.0).
            Not used when "Return NXDOMAIN" is checked.
        ');
echo gettext('
            Direction of the traffic. The default policy is to filter inbound traffic, which sets the policy to the interface originally receiving the traffic.
        ');
echo gettext('
            Domain to override (NOTE: this does not have to be a valid TLD!),
            e.g. \'test\' or \'mycompany.localdomain\' or \'1.168.192.in-addr.arpa\'
        ');
echo gettext('
            IP address of the authoritative DNS server for this domain,
            e.g. \'192.168.100.100\'. To use a nondefault port for communication,
            append an \'@\' with the port number.
        ');
echo gettext('
            If a domain is entered here, queries for this specific domain will be forwarded to the specified server.
            Leave blank to forward all queries to the specified server (default).
        ');
echo gettext('
            If a packet matches a rule specifying quick, then that rule is considered the last matching rule and the specified action is taken.
            When a rule does not have quick enabled, the last matching rule wins.
        ');
echo gettext('
            If enabled, a total number of unwanted replies is kept track of in every thread.
            When it reaches the threshold, a defensive action is taken and a warning is printed to the log file.
            This defensive action is to clear the RRSet and message caches, hopefully flushing away any poison.
        ');
echo gettext('
            If enabled, prints one line per query to the log, with the log timestamp and IP address, name, type and class.
            Note that it takes time to print these lines, which makes the server (significantly) slower. Odd
            (non-printable) characters in names are printed as \'?\'.
        ');
echo gettext('
            If enabled, prints one line per reply to the log, with the log timestamp and IP address, name, type,
            class, return code, time to resolve, whether the reply is from the cache and the response size.
            Note that it takes time to print these lines, which makes the server (significantly) slower. Odd
            (non-printable) characters in names are printed as \'?\'.
        ');
echo gettext('
            If enabled, prints the word \'query: \' and \'reply: \' with logged queries and replies. This makes filtering
            logs easier.
        ');
echo gettext('
            Leave as \'default\' to use the system routing table. Or choose a gateway to utilize policy based routing.
        ');
echo gettext('
            Limits the serving of expired responses to the configured amount of seconds after expiration.
            A value of 0 disables the limit. A suggested value per RFC 8767	is between 86400 (1 day) and 259200 (3	days).
        ');
echo gettext('
            List of domains to mark as private. These domains and all its subdomains are allowed to contain
            private addresses.
        ');
echo gettext('
            Message cache elements are prefetched before they expire to help keep the cache up to date.
            When enabled, this option can cause an increase of around 10% more DNS traffic and load
            on the server, but frequently requested items will not expire from the cache.
        ');
echo gettext('
            Number of hosts for which information is cached.
        ');
echo gettext('
            Packets matching this rule will be mapped to the IP address given here.
        ');
echo gettext('
            Paste a public key of the selected type in X.509 format.
            Must be pasted including the \'-----BEGIN ...-----\' and \'-----END [...]-----\' headers.
        ');
echo gettext('
            Paste an optional private key of the selected type in X.509 format which belongs to the public key specified above.
            When adding the public key of a peer, this field should not be specified as the private key remains solely with the peer.
            Must be pasted including the \'-----BEGIN ...-----\' and \'-----END [...]-----\' headers.
        ');
echo gettext('
            Select the log verbosity. Level 0 means no verbosity, only errors. Level 1 gives operational information.
            Level 2 gives detailed operational information. Level 3 gives query level information, output per query.
            Level 4 gives algorithm level information. Level 5 logs client identification for cache misses.
        ');
echo gettext('
            Send minimum amount of information to upstream servers to enhance privacy.
            Do not fall-back to sending full QNAME to potentially broken nameservers.
            A lot of domains will not be resolvable when this option in enabled.
            Only use if you know what you are doing.
        ');
echo gettext('
            Serve expired responses from the cache with a TTL of 0 without waiting for the actual resolution to finish.
            The TTL can be modified with "Expired Record Reply TTL value"
        ');
echo gettext('
            Set the TTL of expired records to the "TTL for Expired Responses" value after a failed attempt to
            retrieve the record from an upstream server. This makes sure that the expired records will be served as long
            as there are queries for it.
        ');
echo gettext('
            Size of the RRset cache. Contains the actual RR data. Valid input is plain bytes, optionally appended
            with \'k\', \'m\', or \'g\' for kilobytes, megabytes or gigabytes respectively.
        ');
echo gettext('
            Size of the message cache. The message cache stores DNS rcodes and validation statuses.
            The RRSet cache will automatically be set to twice this amount. The RRSet cache contains the actual RR data.
            Valid input is plain bytes, optionally appended with \'k\', \'m\', or \'g\' for kilobytes, megabytes
            or gigabytes respectively.
        ');
echo gettext('
            TTL value to use when replying with expired data. If "Client Expired Response Timeout" is also used
            then it is recommended to use 30 as the value as per RFC 8767.
        ');
echo gettext('
            The Common Name of the DNS server (e.g. dns.example.com). This field is required to verify its TLS certificate.
            DNS-over-TLS is susceptible to man-in-the-middle attacks unless certificates can be verified.
            Leave empty to accept self-signed yet also potentially fraudulent certificates.
        ');
echo gettext('
            The configured system nameservers will be used to forward queries to.
            This will override any entry in the grid below, except for entries with a specific domain.
            DNS over TLS will never be used for any query bound for a system nameserver.
        ');
echo gettext('
            The number of incoming TCP buffers to allocate per thread.
            If 0 is selected then no TCP queries, from clients, are accepted.
        ');
echo gettext('
            The number of outgoing TCP buffers to allocate per thread.
            If 0 is selected then no TCP queries, to authoritative servers, are done.
        ');
echo gettext('
            The number of ports to open. This number of file descriptors can be opened per thread. Larger numbers
            need extra resources from the operating system. For performance a very large value is best.
            For reference, usually double the amount of queries per thread is used.
        ');
echo gettext('
            The number of queries that every thread will service simultaneously. If more queries arrive that
            need to be serviced, and no queries can be jostled out (see "Jostle Timeout"),
            then these queries are dropped. This forces the client to resend after a timeout, allowing the
            server time to work on the existing queries.
        ');
echo gettext('
            This timeout is used for when the server is very busy. Set to a value that usually results in one
            round-trip to the authority servers. If too many queries arrive, then 50% of the queries are allowed
            to run to completion, and the other 50% are replaced with the new incoming query if they have
            already spent more than their allowed time. This protects against denial of service by
            slow queries or high query rates.
        ');
echo gettext('
            Time in milliseconds before replying to the client with expired data. This essentially enables the serve-
            stable behavior as specified in RFC 8767 that first tries to resolve before immediately responding with expired
            data. A recommended value per RF 8767 is 1800. Setting this to 0 will disable this behavior.
        ');
echo gettext('
            Time to live in seconds for entries in the host cache. The host cache contains round-trip timing, lameness
            and EDNS support information.
        ');
echo gettext('
          Leave empty to generate a device name. Custom names are possible, but only if the
          start of the name matches the required prefix and contains numeric characters or
          dots, e.g. "vlan0.1.2" or "qinq0.3.4".
        ');
echo gettext('
          Send alerts in eve format to syslog, using log level info.
          This will not change the alert logging used by the product itself.
          Drop logs will only be send to the internal logger, due to restrictions in suricata.
          ');
echo gettext('
          The interface can be configured in a multicast mode to create a virtual network of hosts.
          This is the IP multicast group address the interface will join.
        ');
echo gettext('
          The interface can be configured in a unicast, or point-to-point, mode to create a tunnel between two hosts.
          This is the IP address of the remote end of the tunnel.
        ');
echo gettext('
          The source address used in the encapsulating IPv4/IPv6 header.
          The address should already be assigned to an existing interface.
          When the interface is configured in unicast mode, the listening socket is bound to this address.
        ');
echo gettext('
          These are addresses on your private network, and are not allowed to be returned for public internet names.
          Any occurrence of such addresses are removed from DNS answers.
          Additionally, the DNSSEC validator may mark the answers bogus.
          This protects against so-called DNS Rebinding.

          (Only applicable when DNS rebind check is enabled in System->Settings->Administration)
        ');
echo gettext('
          When the interface is configured in multicast mode, the dev interface is used to transmit IP multicast packets.
        ');
echo gettext('
         This is the number of packets the packet capture will grab. Default value is 100.
         Enter 0 (zero) for no count limit.
       ');
echo gettext('
         This value is either the Source or Destination IP address or subnet in CIDR notation.
         The packet capture will look for this address in either field.
         Matching can be negated by preceding the value with "not".
         Multiple IP addresses or CIDR subnets may be specified as boolean expression.
         If you leave this field blank, all packets on the specified interface will be captured.

         Example: not 10.0.0.0/24 not and not 11.0.0.1
       ');
echo gettext('(FQ-)CoDel ECN');
echo gettext('(FQ-)CoDel interval');
echo gettext('(FQ-)CoDel target');
echo gettext('(optional) user credentials.');
echo gettext('0: Log everything, Positive Value: Log events that take longer than specified, Negative Value: Log nothing.');
echo gettext('802.1Q VLAN PCP (priority code point)');
echo gettext('802.1Q VLAN tag (between 1 and 4094)');
echo gettext('A JSON document containing configuration options that apply to the local node');
echo gettext('A name for this server. Used when displaying information about this server (logs, info service, etc).');
echo gettext('API Access Token');
echo gettext('AVPair');
echo gettext('Access Control List');
echo gettext('Access Token used for the Zerotier API service');
echo gettext('Access log target');
echo gettext('According to the service type path can be a file or a directory.');
echo gettext('Action');
echo gettext('Action to perform when filter policy applies');
echo gettext('Activate third party signatures from BLURL. Use at your own risk.');
echo gettext('Activate third party signatures from Malware Expert. Use at your own risk.');
echo gettext('Activate third party signatures from Sanesecurtiy BOFHLand. Use at your own risk.');
echo gettext('Activate third party signatures from Sanesecurtiy JURLBLA. Use at your own risk.');
echo gettext('Active Timeout');
echo gettext('Add BLURL Signatures');
echo gettext('Add BOFHLand Signatures');
echo gettext('Add JURLBLA Signatures');
echo gettext('Add Malware Expert Signatures');
echo gettext('Add delay in ms to this pipe.');
echo gettext('Add routes in CIDR notation, e.g. 192.168.2.0/24. Multiple entries are allowed');
echo gettext('Add the networks you want to protect using IPS mode. Warning: if a WAN interface is monitored then local addresses (e.g. 192.168.1.1/24) are not going to be valid!');
echo gettext('Address');
echo gettext('Address Family');
echo gettext('Address(es) or hostname(s) to which this client should connect to separated by comma for multiple entries');
echo gettext('Administrator\'s Email');
echo gettext('Allow 204 responses');
echo gettext('Allow DynFi Manager traffic');
echo gettext('Allow interface subnets');
echo gettext('Allowed IPs');
echo gettext('Allowed MAC addresses');
echo gettext('Allowed SSL ports');
echo gettext('Allowed Subnets');
echo gettext('Allowed addresses');
echo gettext('Allowed destination SSL ports, you may use ranges (ex. 222-226) and add comments with colon (ex. 22:ssh).');
echo gettext('Allowed destination TCP port');
echo gettext('Allowed destination TCP ports, you may use ranges (ex. 222-226) and add comments with colon (ex. 22:ssh).');
echo gettext('Always send accounting requests');
echo gettext('Applications');
echo gettext('Authenticate using');
echo gettext('Authentication Prompt');
echo gettext('Authentication Settings');
echo gettext('Authentication TTL (hours)');
echo gettext('Authentication method');
echo gettext('Authentication processes');
echo gettext('Authorized keys');
echo gettext('Automatic');
echo gettext('Automatically added, will be removed when unused');
echo gettext('Automatically create firewall rules associated to the selected interface(s) and SSH port, allowing Manager traffic to these interfaces.');
echo gettext('Automatically create firewall rules associated to the selected interface(s) and WebGUI port, allowing Manager\'s DirectView access to these interfaces.');
echo gettext('Automatically register in M/Monit by sending Monit credentials (see Monit Access List above).');
echo gettext('Avoid authentication for addresses and subnets in this list');
echo gettext('Avoid authentication for physical addresses in this list');
echo gettext('Bandwidth');
echo gettext('Bandwidth Metric');
echo gettext('Banned host IP addresses');
echo gettext('Base DN');
echo gettext('Beginning Hour');
echo gettext('Bind Password');
echo gettext('Bind User');
echo gettext('Blacklist');
echo gettext('Blacklist destination domains. You may use a regular expression, use a comma or press Enter for new item. Examples: "mydomain.com" matches on "*.mydomain.com"; "^https?:\/\/([a-zA-Z]+)\.mydomain\." matches on "http(s)://textONLY.mydomain.*"; "\.gif$" matches on "*.gif" but not on "\*.gif\test"; "\[0-9]+\.gif$" matches on "\123.gif" but not on "\test.gif"');
echo gettext('Blacklisted domain.');
echo gettext('Block browser/user-agents');
echo gettext('Block encrypted archive');
echo gettext('Block specific MIME type reply');
echo gettext('Block specific MIME type reply. You may use a regular expression, use a comma or press Enter for new item. Examples: "video/flv" matches on "Flash Video"; "application/x-javascript" matches on "javascripts"');
echo gettext('Block user-agents. You may use a regular expression, use a comma or press Enter for new item. Examples: "^(.)+Macintosh(.)+Firefox/37\.0" matches on "Macintosh version of Firefox revision 37.0"; "^Mozilla" matches on "all Mozilla based browsers"');
echo gettext('Buckets');
echo gettext('CA to use');
echo gettext('CRL');
echo gettext('Cache directory location');
echo gettext('Cache size in Megabytes');
echo gettext('Capture local');
echo gettext('Categories');
echo gettext('Certificate');
echo gettext('Certificate to use to connect');
echo gettext('Check TLS Common-Name');
echo gettext('Check if the username should be sent to the ICAP server.');
echo gettext('Check if you want to encode the username using base64.');
echo gettext('Checks that the username given by the user matches the Common-Name of the certificate.');
echo gettext('ChilliSpot Bandwith Max DOWN');
echo gettext('ChilliSpot Bandwith Max UP');
echo gettext('Choose If in case any case you want to ensure a match to evaluate as is, else choose unless if you want the negated version. Unless is used if you want to use the proxy for every host but not for some special ones.');
echo gettext('Choose a proxy type. Usually you should use Direct for a direct connection or Proxy for a Proxy.');
echo gettext('Choose a secure value. It is recommended that you generate this password.');
echo gettext('Choose for which file types to scan, if unsure select all.');
echo gettext('Choose the Root CA. This CA will be trusted to issue client certificates for authentication.');
echo gettext('Choose the certificate the Radius service should use.');
echo gettext('Choose what to do with packets that match the criteria specified below.
            Hint: the difference between block and reject is that with reject, a packet (TCP RST or ICMP port unreachable for UDP) is returned to the sender, whereas with block the packet is dropped silently. In either case, the original packet is discarded.
        ');
echo gettext('Choose which applications should be forwarded to the specified target, omit to select all.');
echo gettext('Choose which facilities to include, omit to select all.');
echo gettext('Choose which gateway this route applies to or <a href="/system_gateways_edit.php">add a new one</a>.');
echo gettext('Choose which levels to include, omit to select all.');
echo gettext('ClamAV engine version');
echo gettext('ClamAV log verbose');
echo gettext('ClamAV will scan within archives and compressed files.');
echo gettext('Client Expired Response Timeout');
echo gettext('Clients will be disconnected after this amount of inactivity. They may log in again immediately, though. Enter 0 to disable idle timeout.');
echo gettext('Clients will be disconnected after this amount of time, regardless of activity. They may log in again immediately, though. Enter 0 to disable hard timeout (not recommended unless an idle timeout is set).');
echo gettext('Collect IPS Events');
echo gettext('Collect NetFlow data on this firewall for use with Insight. Note that the local cache only holds the latest 100 MB of data.');
echo gettext('Color');
echo gettext('Comma-separated list of SMTP servers for alert delivery.');
echo gettext('Command');
echo gettext('Community Mode');
echo gettext('Concurrent user logins');
echo gettext('Condition');
echo gettext('Connection Timeout');
echo gettext('Count');
echo gettext('Create a list of sites which may not be inspected, for example bank sites. Prefix the domain with a . to accept all subdomains (e.g. .google.com).');
echo gettext('Custom config');
echo gettext('Custom configuration, which will be returned in the output file without modifications');
echo gettext('Custom template');
echo gettext('DHCP Enable');
echo gettext('DHCP Listen IP');
echo gettext('DNS Mode');
echo gettext('DNS Server');
echo gettext('DSCP');
echo gettext('Database Count');
echo gettext('Day of the month');
echo gettext('Days of the week');
echo gettext('Decode mail files');
echo gettext('Default EAP Type');
echo gettext('Default Options TTL');
echo gettext('Default ttl');
echo gettext('Define the Fallback VLAN group ID.');
echo gettext('Delay');
echo gettext('Depends');
echo gettext('Description');
echo gettext('Description to be displayed in the "jobs" tab.');
echo gettext('Description to identify this pipe.');
echo gettext('Description to identify this queue.');
echo gettext('Description to identify this rule.');
echo gettext('Description to identify this zone.');
echo gettext('Destination');
echo gettext('Destination / Invert');
echo gettext('Destination Address');
echo gettext('Destination IP');
echo gettext('Destination network for this static route');
echo gettext('Destination port');
echo gettext('Destination port number or well known name (imap, imaps, http, https, ...)');
echo gettext('Destination port number or well known name (imap, imaps, http, https, ...), for ranges use a dash');
echo gettext('Destinations');
echo gettext('Detect Profile');
echo gettext('Detect broken executables');
echo gettext('Device');
echo gettext('Direction');
echo gettext('Disable 204 responses outside previews for virus_scan if your ICAP client does not support it.');
echo gettext('Disable Commands');
echo gettext('Disable Routes');
echo gettext('Disable cache');
echo gettext('Disable password save');
echo gettext('Disabled');
echo gettext('Do not decode and/or filter SSL content, only log requested domains and IP addresses. Some old servers may not provide SNI, so their addresses will not be indicated.');
echo gettext('Do not send alerts for the following events but on all others.');
echo gettext('Domain');
echo gettext('Domain Level From');
echo gettext('Domain Level To');
echo gettext('Domain of the host, e.g. example.com');
echo gettext('Drop Categories (IPS)');
echo gettext('Drop Continents (IPS)');
echo gettext('Drop Countries (IPS)');
echo gettext('Drop Protocols (IPS)');
echo gettext('Drop Risky Flows (IPS)');
echo gettext('Dst-port');
echo gettext('DynFi Manager binding');
echo gettext('Dynamic pipe creation by source or destination address.
        <li>Choose destination to give every IP in destination field of rules the specified bandwidth. A pipe with 1Mbit e.g. would let 3 clients lend 1Mbit each so 3Mbit max. Normally this is used for download pipes.</li>
        <li>Choose source to give every IP in the source field of rules the specified bandwidth. Normally this is used for upload pipes.</li>
        <li>Leave this value empty if you want to create a pipe with a fixed bandwidth.</li>
        ');
echo gettext('Dynamic queue creation by source or destination address.
        <li>Choose destination to evenly share every IP in destination field of rules the specified bandwidth. A pipe with 1Mbit e.g. would let 4 clients lend 250Kbit each. Normally this is used for download queues.</li>
        <li>Choose source to evenly share every IP in the source field of rules the specified bandwidth. Normally this is used for upload queues.</li>
        <li>Leave this value empty if you want to specify multiple queues with different weights.</li>
        ');
echo gettext('EXOS VLAN Tagged list');
echo gettext('EXOS VLAN Untagged');
echo gettext('EXOS policy');
echo gettext('Elliptic Curve');
echo gettext('Enable');
echo gettext('Enable Authentication');
echo gettext('Enable ChilliSpot attributes');
echo gettext('Enable ClamAV');
echo gettext('Enable ClamAV verbose logging.');
echo gettext('Enable CoDel');
echo gettext('Enable CoDel active queue management');
echo gettext('Enable DNS v4 first');
echo gettext('Enable Daily Session Limit');
echo gettext('Enable DirectView access');
echo gettext('Enable EXOS attributes');
echo gettext('Enable Freshclam verbose logging.');
echo gettext('Enable HTTPD');
echo gettext('Enable ICAP');
echo gettext('Enable IPS Mode');
echo gettext('Enable LDAP');
echo gettext('Enable Linux Package Cache');
echo gettext('Enable Mikrotik attributes');
echo gettext('Enable Monit');
echo gettext('Enable PIE');
echo gettext('Enable PIE active queue management');
echo gettext('Enable Parent Proxy');
echo gettext('Enable Preview');
echo gettext('Enable Protected Mode');
echo gettext('Enable Redis');
echo gettext('Enable Remote MySQL');
echo gettext('Enable SNMP Agent');
echo gettext('Enable SQLite');
echo gettext('Enable SSL inspection');
echo gettext('Enable SSL inspection mode, which allows to log HTTPS connections information, such as requested URL and/or make the proxy act as a man in the middle between the internet and your clients. Be aware of the security implications before enabling this option. If you plan to use transparent HTTPS mode, you need nat rules to reflect your traffic.<a href="/firewall_nat_edit.php?template=transparent_proxy&https=1">Add a new firewall rule </a>');
echo gettext('Enable Syslog');
echo gettext('Enable Syslog logging.');
echo gettext('Enable TCP port');
echo gettext('Enable Transparent HTTP proxy');
echo gettext('Enable Transparent mode');
echo gettext('Enable VLAN assignment');
echo gettext('Enable VLAN fallback assignment');
echo gettext('Enable WISPr attributes');
echo gettext('Enable Windows Update Cache');
echo gettext('Enable WireGuard');
echo gettext('Enable access logging');
echo gettext('Enable access logging.');
echo gettext('Enable alert');
echo gettext('Enable authentication against the parent proxy.');
echo gettext('Enable blacklisting of this domain.');
echo gettext('Enable c-icap service');
echo gettext('Enable clamd service');
echo gettext('Enable encryption for mail server communication.');
echo gettext('Enable eve syslog output');
echo gettext('Enable freshclam service');
echo gettext('Enable if you want to use previews.');
echo gettext('Enable intrusion detection system.');
echo gettext('Enable local cache');
echo gettext('Enable nProbe');
echo gettext('Enable ntopng');
echo gettext('Enable or disable SSL server certificate verification.');
echo gettext('Enable or disable alert.');
echo gettext('Enable or disable monit.');
echo gettext('Enable or disable service checks.');
echo gettext('Enable or disable the Redis service.');
echo gettext('Enable or disable the caching of Windows updates. This makes sense if you don\'t have a WSUS server. If you can setup a WSUS server, this solution should be preferred.');
echo gettext('Enable or disable the caching of packages for linux distributions. This makes sense if you have multiple servers in your network and do not host your own package mirror. This will reduce internet traffic usage but increase disk access.');
echo gettext('Enable or disable the local cache. Only UFS directory cache type is supported. Do not enable on embedded systems with SD or CF cards as this will wear down your drive.');
echo gettext('Enable or disable the proxy service.');
echo gettext('Enable or disable the squid SNMP Agent.');
echo gettext('Enable or disable this server.');
echo gettext('Enable or disable traffic management.');
echo gettext('Enable parent proxy feature.');
echo gettext('Enable pinger');
echo gettext('Enable promiscuous mode, for certain setups (like IPS with vlans), this is required to actually capture data on the physical interface.');
echo gettext('Enable protection mode (block traffic).<br />Before enabling, please disable all hardware offloading first <a href="/system_advanced_network.php">in advanced network</a>.');
echo gettext('Enable proxy');
echo gettext('Enable ruleset');
echo gettext('Enable service checks');
echo gettext('Enable store logging');
echo gettext('Enable store logging.');
echo gettext('Enable syslog alerts');
echo gettext('Enable the logging of authentication requests, including MAC addresses.');
echo gettext('Enable the override for this host');
echo gettext('Enable the usage of DNS blocklists.');
echo gettext('Enable this alias for the selected host');
echo gettext('Enable this domain override');
echo gettext('Enable this fingerprint rule.');
echo gettext('Enable this pipe and its related queues and rules');
echo gettext('Enable this policy.');
echo gettext('Enable this queue and its related rules');
echo gettext('Enable this rule');
echo gettext('Enable this rule.');
echo gettext('Enable this zone');
echo gettext('Enable traffic management.');
echo gettext('Enable transparent ftp proxy mode to forward all requests for destination port 21 to the proxy server without any additional configuration.');
echo gettext('Enable transparent proxy mode. You will need a firewall rule to forward traffic from the firewall to the proxy server. You may leave the proxy interfaces empty, but remember to set a valid ACL in that case. <a href="/firewall_nat_edit.php?template=transparent_proxy"> Add a new firewall rule </a>');
echo gettext('Enable whitelisting of this domain.');
echo gettext('Enabled');
echo gettext('Encode Username');
echo gettext('Endpoint Address');
echo gettext('Endpoint Port');
echo gettext('Enforce local group');
echo gettext('Enter a URL pattern like dynfi.com/forum*.');
echo gettext('Enter a description for this proxy for your reference.');
echo gettext('Enter a description for this rule. The description should help you to identify this rule.');
echo gettext('Enter a description to explain what this blacklist is intended for.');
echo gettext('Enter a description to explain what this job is intended for.');
echo gettext('Enter a filename for storing the blacklist.');
echo gettext('Enter a hostname pattern like *.dynfi.com.');
echo gettext('Enter a name for this category.');
echo gettext('Enter a name for this key pair. The name should help you to identify this key pair.');
echo gettext('Enter a name for this match.');
echo gettext('Enter a proxy URL in the form proxy.example.com:3128.');
echo gettext('Enter a valid TCP port.');
echo gettext('Enter an url to fetch the blacklist from.');
echo gettext('Enter parameters for this job if required.');
echo gettext('Enter start hour (minimum 0).');
echo gettext('Enter the URL of the ICAP Server');
echo gettext('Enter the allowed overall bandwidth in kilobits per second (leave empty to disable).');
echo gettext('Enter the allowed per host bandwidth in kilobits per second (leave empty to disable).');
echo gettext('Enter the cache memory size to use or zero to disable completely.');
echo gettext('Enter the days of the month for the job to act, can also be a comma-separated list, * (each) or a range (ex. 1,20,28 or 1-28)');
echo gettext('Enter the days of the week for the job to act, can also be a comma-separated list, * (each) or a range (ex. 1,2,3 or 1-3)');
echo gettext('Enter the default ttl.');
echo gettext('Enter the directory location for the local cache (default is /var/squid/cache).');
echo gettext('Enter the end time (maximum 23, minimum 0 or start time).');
echo gettext('Enter the first day of the week.');
echo gettext('Enter the first month.');
echo gettext('Enter the hours for the job to act, can also be a comma-separated list, * (each) or a range (ex. 10,11,12 or 10-12)');
echo gettext('Enter the last day of the week.');
echo gettext('Enter the last month (maximum December, minimum January or From Month).');
echo gettext('Enter the maximum amount of dots in the domain name.');
echo gettext('Enter the maximum size (in MB) to use for SSL certificates.');
echo gettext('Enter the maximum size for downloads in kilobytes (leave empty to disable).');
echo gettext('Enter the maximum size for uploads in kilobytes (leave empty to disable).');
echo gettext('Enter the minimum amount of dots in the domain name.');
echo gettext('Enter the minutes for the job to act, can also be a comma-separated list, * (each) or a range (ex. 10,20,30 or 10-30)');
echo gettext('Enter the months for the job to act, can also be a comma-separated list, * (each) or a range (ex. 1,2,3 or 1-3)');
echo gettext('Enter the name of the header.');
echo gettext('Enter the network address to match in CIDR notation for example like 127.0.0.1/8 or ::1/128');
echo gettext('Enter the number of first-level subdirectories for the local cache (default is 16).');
echo gettext('Enter the number of first-level subdirectories for the local cache (default is 256).');
echo gettext('Enter the number of ssl certificate workers to use (sslcrtd_children).');
echo gettext('Enter the size of the preview which is sent to the ICAP server.');
echo gettext('Enter the size of the preview.');
echo gettext('Enter the storage size for the local cache (default is 100).');
echo gettext('Enter the url where the REQMOD requests should be sent to.');
echo gettext('Enter the url where the RESPMOD requests should be sent to.');
echo gettext('Eventqueue Path');
echo gettext('Eventqueue Slots');
echo gettext('Events');
echo gettext('Events ZMQ Endpoint (IPS)');
echo gettext('Exclusion List');
echo gettext('Exclusion list destination domains.You may use a regular expression, use a comma or press Enter for new item. Examples: "mydomain.com" matches on "*.mydomain.com"; "https://([a-zA-Z]+)\.mydomain\." matches on "http(s)://textONLY.mydomain.*"; "\.gif$" matches on "\*.gif" but not on "\*.gif\test"; "\[0-9]+\.gif$" matches on "\123.gif" but not on "\test.gif"');
echo gettext('Executable and Linking Format is a standard format for UN*X executables.');
echo gettext('Expire idle flows.');
echo gettext('Expired Record Reply TTL value');
echo gettext('Explicit Congestion Notification');
echo gettext('Export type');
echo gettext('Extended Statistics');
echo gettext('Extended pre auth data');
echo gettext('FQ-CoDel flows');
echo gettext('FQ-CoDel limit');
echo gettext('FQ-CoDel quantum');
echo gettext('FTP Proxy Settings');
echo gettext('FTP proxy interfaces');
echo gettext('FTP proxy port');
echo gettext('Facilities');
echo gettext('Fallback VLAN ID');
echo gettext('File format to export.');
echo gettext('Filename');
echo gettext('Files larger than this limit won\'t be scanned.');
echo gettext('Filter for group objects, should match all available group objects a user might be a member of.');
echo gettext('Find the process by regular expression. Test your pattern with <br><b>monit procmatch <i>PATTERN</i></b>');
echo gettext('Follow directory symlinks');
echo gettext('Follow regular file symlinks');
echo gettext('Forward HTTP traffic to transparent proxy');
echo gettext('Forward HTTPS traffic to transparent proxy');
echo gettext('Forward Proxy');
echo gettext('Freshclam connect timeout');
echo gettext('Freshclam database mirror');
echo gettext('Freshclam log verbose');
echo gettext('From Day');
echo gettext('From Month');
echo gettext('Gateway');
echo gettext('Gateway IP');
echo gettext('General Forward Settings');
echo gettext('General Proxy Settings');
echo gettext('General Redis Settings');
echo gettext('General Settings');
echo gettext('Given name, last name, or anything you need to describe.');
echo gettext('Google GSuite restricted');
echo gettext('Group Filter');
echo gettext('HTTP Port');
echo gettext('HTTP Port this service listens on.');
echo gettext('HTTPS Port');
echo gettext('HTTPS Port this service listens on. If you enable HTTPS you will be redirected from HTTP to HTTPS. Please select a certificate below');
echo gettext('Hard timeout (minutes)');
echo gettext('Harden DNSSEC Data');
echo gettext('Hide Identity');
echo gettext('Hide Version');
echo gettext('Home networks');
echo gettext('Host');
echo gettext('Host Address');
echo gettext('Host Pattern');
echo gettext('Host name of MX host, e.g. mail.example.com');
echo gettext('Host override');
echo gettext('Hostname');
echo gettext('Hostname (of this machine) to redirect login page to, leave blank to use this interface IP address, otherwise make sure the client can access DNS to resolve this location. When using a SSL certificate, make sure both this name and the cert name are equal.');
echo gettext('Hostname or IP');
echo gettext('Hostname or address to resolve.');
echo gettext('Hours');
echo gettext('ICAP Settings');
echo gettext('ICP port');
echo gettext('IP Address');
echo gettext('IP Address or Network with CIDR');
echo gettext('IP address');
echo gettext('IP address of DNS server to forward all requests.');
echo gettext('IP address of the host, e.g. 192.168.100.100 or fd00:abcd::1');
echo gettext('IP addresses of DynFi Manager instance.');
echo gettext('IPS mode');
echo gettext('IPs of DynFi Manager');
echo gettext('IPv6 Address');
echo gettext('Idle timeout');
echo gettext('Idle timeout (minutes)');
echo gettext('If Custom is specified. The detection engine tries to split out separate signatures into groups so that a packet is only inspected against signatures that can actually match. As in large rule set this would result in way too many groups and memory usage similar groups are merged together.');
echo gettext('If enabled, extended statistics are printed.');
echo gettext('If enabled, id.server and hostname.bind queries are refused.');
echo gettext('If enabled, version.server and version.bind queries are refused.');
echo gettext('If provided, all traffic will be transmitted over an HTTPS connection to protect against eavesdroppers.');
echo gettext('If set (default), Squid will include a Via header in requests and replies as required by RFC2616.');
echo gettext('If the number of the available threads is less than number, the c-icap server starts a new child.');
echo gettext('If the number of the available threads is more than number then the c-icap server kills a child.');
echo gettext('If this checkbox is checked, you can use an ICAP server to filter or replace content.');
echo gettext('If this option is set, users can login on multiple machines at once. If disabled subsequent logins will cause machines previously logged in with the same username to be disconnected.');
echo gettext('If you enable this option, the client IP address will be sent to the ICAP server. This can be useful if you want to filter traffic based on IP addresses.');
echo gettext('If you enable this option, the username of the client will be sent to the ICAP server. This can be useful if you want to filter traffic based on usernames. Authentication is required to use usernames.');
echo gettext('If you turn off this option, the original files will still be scanned, but without parsing individual messages/attachments.');
echo gettext('If you use previews, only a part of the data is sent to the ICAP server. Setting this option can improve the performance.');
echo gettext('Ignore SSL certificate validation (for self-signed certificates)');
echo gettext('Ignore hosts in access.log');
echo gettext('Inactive Timeout');
echo gettext('Incoming TCP Buffers');
echo gettext('Inner-Tunnel LDAP');
echo gettext('Insecure Domains');
echo gettext('Insert here the domain that will be allowed to use Google GSuite.
                All accounts that are not in this domain will be blocked to use it.');
echo gettext('Instance');
echo gettext('Interface');
echo gettext('Interface 2');
echo gettext('Interfaces');
echo gettext('Interfaces bound to DynFi Manager.');
echo gettext('Interfaces to capture.');
echo gettext('Internal number used for this zone');
echo gettext('Interval before dropping packets (in ms), leave empty for default');
echo gettext('Invert Port');
echo gettext('Invert Protocol');
echo gettext('Invert destination');
echo gettext('Invert source');
echo gettext('Join Type');
echo gettext('Jostle Timeout');
echo gettext('Keepalive Interval');
echo gettext('Key Type');
echo gettext('Last Hour');
echo gettext('Last updated');
echo gettext('Last updated timestamp. This is the time the vendor created the lists.');
echo gettext('Let the Redis server listen on non-localhost interfaces.');
echo gettext('Levels');
echo gettext('License Key');
echo gettext('License key for activating nProbe Pro.');
echo gettext('License key for activating ntopng Enterprise.');
echo gettext('Limits');
echo gettext('List of IP addresses not to be sent via parent proxy.');
echo gettext('List of addresses allowed to pass trough the tunnel adapter. Please use CIDR notation like 10.0.0.1/24.');
echo gettext('List of addresses to configure on the tunnel adapter. Please use CIDR notation like 10.0.0.1/24.');
echo gettext('List of authorized SSH keys.');
echo gettext('List of domains from where blocklist will be downloaded.');
echo gettext('List of domains not to be sent via parent proxy.');
echo gettext('List of domains to mark as insecure. DNSSEC chain of trust is ignored towards the domain name.');
echo gettext('List of domains to mark as private. You only need this for some DNSBL lists which resolve to private addresses.');
echo gettext('List of peers for this server.');
echo gettext('List with events. Leave it empty for all events.');
echo gettext('Listen Interfaces');
echo gettext('Listen Port');
echo gettext('Listen address');
echo gettext('Listening interfaces');
echo gettext('Load the certificate and private key from the Windows Certificate System Store (Windows/OpenSSL Only).');
echo gettext('Local Cache Settings');
echo gettext('Local Description');
echo gettext('Local Description to help identify this network');
echo gettext('Local Domains');
echo gettext('Local IPs');
echo gettext('Local Networks (IPS)');
echo gettext('Location to fetch geoip address ranges from. Refer to the DynFi Firewall documentation for
        further details');
echo gettext('Log');
echo gettext('Log Authentication Bad Password');
echo gettext('Log Authentication Good Password');
echo gettext('Log Authentication Request');
echo gettext('Log File');
echo gettext('Log Level');
echo gettext('Log Level Verbosity');
echo gettext('Log Queries');
echo gettext('Log Replies');
echo gettext('Log SNI information only');
echo gettext('Log Transactions Slower Than (microsecond)');
echo gettext('Log package payload');
echo gettext('Log packets that are handled by this rule');
echo gettext('Log to File or Syslog');
echo gettext('Login-Time');
echo gettext('Logs password if it is correct.');
echo gettext('Logs password if it is rejected.');
echo gettext('M/Monit Register Credentials');
echo gettext('M/Monit Timeout');
echo gettext('M/Monit URL');
echo gettext('MAC Address');
echo gettext('MTU');
echo gettext('MX Host');
echo gettext('MX Priority');
echo gettext('Mail Server Address');
echo gettext('Mail Server Password');
echo gettext('Mail Server Port');
echo gettext('Mail Server SSL Connection');
echo gettext('Mail Server Username');
echo gettext('Mail format');
echo gettext('Make sure the script is executable by the Monit service.');
echo gettext('Mark encrypted archives as viruses (Encrypted.Zip, Encrypted.RAR).');
echo gettext('Mask');
echo gettext('Match');
echo gettext('Match Type');
echo gettext('Match against one or multiple DSCP values.');
echo gettext('Matches');
echo gettext('Max Daily Session');
echo gettext('Max Packet Length');
echo gettext('Max directory recursion');
echo gettext('Max file size');
echo gettext('Max files');
echo gettext('Max keepalive requests');
echo gettext('Max keepalive timeout');
echo gettext('Max object size');
echo gettext('Max recursion');
echo gettext('Max requests per child');
echo gettext('Max scan size');
echo gettext('Max servers');
echo gettext('Max spare threads');
echo gettext('Maximum Clients');
echo gettext('Maximum Length');
echo gettext('Maximum Memory');
echo gettext('Maximum Memory Policy');
echo gettext('Maximum Memory Samples');
echo gettext('Maximum TTL for RRsets and messages');
echo gettext('Maximum depth directories are scanned at.');
echo gettext('Maximum download size (kB)');
echo gettext('Maximum number of queued items');
echo gettext('Maximum number of queued items (including those being processed by MaxThreads threads). It is recommended to have this value at least twice MaxThreads if possible.');
echo gettext('Maximum number of threads running');
echo gettext('Maximum number of threads running at the same time.');
echo gettext('Maximum object size (MB)');
echo gettext('Maximum object size in memory (KB)');
echo gettext('Maximum upload size (kB)');
echo gettext('Memory Cache size in Megabytes');
echo gettext('Memory cache mode');
echo gettext('Message');
echo gettext('Message Cache Size');
echo gettext('Mikrotik VLAN ID');
echo gettext('Mikrotik VLAN Type');
echo gettext('Min spare threads');
echo gettext('Minimum TTL for RRsets and messages');
echo gettext('Minimum acceptable persistent queue delay (in ms), leave empty for default');
echo gettext('Minutes');
echo gettext('Monit HTTPD Access List');
echo gettext('Monit HTTPD Port');
echo gettext('Months');
echo gettext('Multicast group');
echo gettext('MySQL Database');
echo gettext('MySQL Password');
echo gettext('MySQL Port');
echo gettext('MySQL Server');
echo gettext('MySQL User');
echo gettext('Name');
echo gettext('Name of the host, without the domain part. Use "*" to create a wildcard entry.');
echo gettext('Negate');
echo gettext('Negate this match. For example you can match if a host is not inside a network.');
echo gettext('Nested archives are scanned recursively, e.g. if a Zip archive contains a RAR file, all files within it will also be scanned.');
echo gettext('Netmask');
echo gettext('Network');
echo gettext('Network Address');
echo gettext('Network ID');
echo gettext('Network address that the c-icap server uses to listen to requests.');
echo gettext('Networks to interpret as local');
echo gettext('New action');
echo gettext('Not on');
echo gettext('Number of Hosts to cache');
echo gettext('Number of files to be scanned within an archive, a document, or any other container file.');
echo gettext('Number of first-level subdirectories');
echo gettext('Number of logs to keep.');
echo gettext('Number of queries per thread');
echo gettext('Number of second-level subdirectories');
echo gettext('OLE2 block macros');
echo gettext('Offer extended data to the login template before authentication  (mac addresses for upstream use).');
echo gettext('On system boot wait before Monit starts checking services.');
echo gettext('Only VLAN capable interfaces will be shown.');
echo gettext('Only if the object is bigger than size then the percentage of data which defined by SendPercentData sent by the c-icap server before receiving the complete body of request.');
echo gettext('Operator');
echo gettext('Optional DNS server address.');
echo gettext('Optionally define a (list of) service(s) which are required before monitoring this one, if any of the dependencies are either stopped or unmonitored this service will stop/unmonitor too.');
echo gettext('Optionally set a fixed port for this instance to listen on. The standard port range starts at 51820.');
echo gettext('Outgoing Range');
echo gettext('Outgoing TCP Buffers');
echo gettext('Overall bandwidth throttling (kbps)');
echo gettext('P12 Password/confirm');
echo gettext('PE stands for Portable Executable - it\'s an executable file format used in all 32 and 64-bit versions of Windows operating systems.');
echo gettext('PID File');
echo gettext('Packet Length');
echo gettext('Parameters');
echo gettext('Parent');
echo gettext('Parent Proxy Settings');
echo gettext('Parent proxy IP address or hostname.');
echo gettext('Parent proxy port.');
echo gettext('Pass on error');
echo gettext('Pass the content instead of blocking it, in the case when the virus scanner or the virus_scan module finds an error.');
echo gettext('Password');
echo gettext('Password for the bind user.');
echo gettext('Path');
echo gettext('Pattern matcher');
echo gettext('Peers');
echo gettext('Per host bandwidth throttling (kbps)');
echo gettext('Perform HTML normalisation and decryption of MS Script Encoder code.');
echo gettext('Performance and Monitoring');
echo gettext('Pipe');
echo gettext('Please select a separator to join the matches. Or means any mach can be true which can be used to configure the same proxy for multiple networks while And means all matches must be true which can be used to assign the proxy in a more detailed way.');
echo gettext('Please select if this rule should be added to the PAC file.');
echo gettext('Policies are processed on a first match basis a lower number means more important.');
echo gettext('Policy zone will be enabled only for client IP addresses defined by selected network aliases.');
echo gettext('Poll Time');
echo gettext('Polling Interval');
echo gettext('Polling interval in seconds.');
echo gettext('Port');
echo gettext('Port of DNS server, for usual DNS use 53, if you use DoT set it to 853.');
echo gettext('Port on which OpenVPN listens');
echo gettext('Port used by DynFi Manager.');
echo gettext('Prefetch DNS Key Support');
echo gettext('Prefetch Support');
echo gettext('Preview Size');
echo gettext('Priority');
echo gettext('Priority of MX record, e.g. 10');
echo gettext('Private Domains');
echo gettext('Private Key');
echo gettext('Private key of this instance. You can specify your own one, or a key will be generated after saving. Please keep this key safe.');
echo gettext('Program Timeout');
echo gettext('Promiscuous');
echo gettext('Promiscuous mode');
echo gettext('Protocol');
echo gettext('Protocol Type');
echo gettext('Proxies');
echo gettext('Proxy Type');
echo gettext('Proxy interfaces');
echo gettext('Proxy port');
echo gettext('Public Key');
echo gettext('Public key of this instance.');
echo gettext('Public key of this instance. You can specify your own one, or a key will be generated after saving.');
echo gettext('Queue');
echo gettext('Quick');
echo gettext('RRset Cache Size');
echo gettext('Rebind protection networks');
echo gettext('Recipient');
echo gettext('Regular expressions are allowed.');
echo gettext('Reject Connections from other IP addresses than ::1 and 127.0.0.1.');
echo gettext('Reminder');
echo gettext('Remote Access Server');
echo gettext('Remote address');
echo gettext('Request Modify URL');
echo gettext('Reset Expired Record TTL');
echo gettext('Response Modify URL');
echo gettext('Restrict access to users in the selected (local)group. <br/>
                <b>NOTE:</b> please be aware that users (or vouchers) which aren\'t administered locally will be denied when using this option.
                ');
echo gettext('Restrict access to users in the selected (local)group. <br/>
        <b>NOTE:</b> please be aware that users (or vouchers) which aren\'t administered locally will be denied when using this option.');
echo gettext('Restrict to');
echo gettext('Restrictions');
echo gettext('Return NXDOMAIN');
echo gettext('Revision');
echo gettext('Root Certificate');
echo gettext('Rotate alert logs at provided interval.');
echo gettext('Rotate log');
echo gettext('Routes');
echo gettext('Rule configured action');
echo gettext('Rules');
echo gettext('Rulesets');
echo gettext('SID');
echo gettext('SNMP Agent Settings');
echo gettext('SNMP password');
echo gettext('SNMP port');
echo gettext('SSL Proxy port');
echo gettext('SSL Version');
echo gettext('SSL cache size');
echo gettext('SSL cert workers');
echo gettext('SSL certificate');
echo gettext('SSL no bump sites');
echo gettext('SSL/Fingerprint');
echo gettext('Save logs');
echo gettext('Scan HTML');
echo gettext('Scan HWP3');
echo gettext('Scan OLE2');
echo gettext('Scan PDF files');
echo gettext('Scan SWF');
echo gettext('Scan XMLDOCS');
echo gettext('Scan archives');
echo gettext('Scan executable and linking format');
echo gettext('Scan for filetypes');
echo gettext('Scan portable executable');
echo gettext('Scheduler type');
echo gettext('Secret');
echo gettext('Security Settings');
echo gettext('Select Authentication method');
echo gettext('Select NetFlow version to use.');
echo gettext('Select a Certificate Authority to use. To create a CA, go to <a href="/system_camanager.php">CA Manager</a>.');
echo gettext('Select a name for this match.');
echo gettext('Select all the interfaces to enable NetFlow on.');
echo gettext('Select an OpenVPN server to export profiles for.');
echo gettext('Select authentication methods to use, leave empty for no authentication needed.');
echo gettext('Select destinations to send NetFlow data to (ip address:port, eg 192.168.0.1:2550).');
echo gettext('Select how detailed the logs should be debug is the most verbose setting.');
echo gettext('Select if job is enabled or not');
echo gettext('Select if you want to use ICAP.');
echo gettext('Select interface(s) the ftp proxy will bind to.');
echo gettext('Select interface(s) the proxy will bind to.');
echo gettext('Select interface(s) to enable for captive portal.');
echo gettext('Select interface(s) to use. When enabling IPS, only use physical interfaces here (no vlans etc).');
echo gettext('Select interfaces used for WAN traffic to avoid counting NAT traffic twice.');
echo gettext('Select some matches you want to use in this rule. This matches are joined using the selected separator.');
echo gettext('Select the Youtube filter level.');
echo gettext('Select the applicable protocol');
echo gettext('Select the associated host override to apply this alias on');
echo gettext('Select the categories you want to drop. All the traffic belonging to the categories selected is going to be dropped');
echo gettext('Select the command that needs to be executed at given time frame.');
echo gettext('Select the configured AVPairs for this user.');
echo gettext('Select the continents you want to drop. All the traffic coming from the selected continents is going to be dropped');
echo gettext('Select the countries you want to drop. All the traffic coming from the selected countries is going to be dropped');
echo gettext('Select the interface to listen to.');
echo gettext('Select the interface to listen to. Set to none if you want to choose the interface via ntopng UI.');
echo gettext('Select the multi-pattern matcher algorithm to use.');
echo gettext('Select the protocol to capture, Any to omit this filter.');
echo gettext('Select the protocols you want to drop. All the traffic having the protocols selected is going to be dropped');
echo gettext('Select the risky flows you want to drop. All the traffic having the selected flow risks is going to be dropped');
echo gettext('Select the type of the key pair. Currently RSA is the only supported type.');
echo gettext('Select the type of the match. Depending on the match, you will need different arguments.');
echo gettext('Select the type of traffic to be captured, either Any, IPv4 only or IPv6 only.');
echo gettext('Select what to do with URI that contain whitespaces. The current Squid implementation of encode and chop violates RFC2616 by not using a 301 redirect after altering the URL.');
echo gettext('Select what to do with X-Forwarded-For header. If set to: "on", Squid will append your client\'s IP address in the HTTP requests it forwards. By default it looks like X-Forwarded-For: 192.1.2.3; If set to: "off", it will appear as X-Forwarded-For: unknown; "transparent", Squid will not alter the X-Forwarded-For header in any way; If set to: "delete", Squid will delete the entire X-Forwarded-For header; If set to: "truncate", Squid will remove all existing X-Forwarded-For entries, and place the client IP as the sole entry.');
echo gettext('Select which kind of DNSBL you want to use.');
echo gettext('Send Client IP');
echo gettext('Send Username');
echo gettext('Send a reminder after some cycles');
echo gettext('Send alerts to system log in fast log format. This will not change the alert logging used by the product itself.');
echo gettext('Send log data to the selected target. When syslog is selected, facility local 4 will be used to send messages of info level for these logs.');
echo gettext('Send package payload to the log for further analyses.');
echo gettext('Send percentage data');
echo gettext('Send the client IP address to the ICAP server.');
echo gettext('Sequence');
echo gettext('Serve Expired Responses');
echo gettext('Server');
echo gettext('Server Certificate');
echo gettext('Server IP');
echo gettext('Server Password');
echo gettext('Server Port');
echo gettext('Server admin');
echo gettext('Servername');
echo gettext('Service Type');
echo gettext('Set a list of DNS servers for this pool.');
echo gettext('Set a password if parent proxy requires authentication.');
echo gettext('Set a username if parent proxy requires authentication.');
echo gettext('Set action to perform here, only used when in IPS mode.');
echo gettext('Set database name of remote MySQL server.');
echo gettext('Set exos policy filter id with Filter-ID="Entrasys:version=1:mgmt=su:policy=[policy_name]"');
echo gettext('Set exos vlan tagged');
echo gettext('Set exos vlan untagged');
echo gettext('Set how many times one account is allowed to login at the same time.');
echo gettext('Set minimum TLS version. Please be aware that every version below 1.2 is considered as insecure.');
echo gettext('Set persistent keepalive interval in seconds.');
echo gettext('Set port the endpoint listens to.');
echo gettext('Set public IP address the endpoint listens to.');
echo gettext('Set the "shortname" for the client.');
echo gettext('Set the Base DN in format dc=example,dc=domain,dc=com');
echo gettext('Set the Elliptical cryptography configuration.');
echo gettext('Set the IP address for this static lease.');
echo gettext('Set the IP address of remote MySQL server.');
echo gettext('Set the IP address of the remote client or the complete network like 10.10.10.0/24');
echo gettext('Set the IP address the user should receive.');
echo gettext('Set the IP address to listen on.');
echo gettext('Set the IPv6 address the user should receive.');
echo gettext('Set the MAC address for this static lease.');
echo gettext('Set the Mikrotik VLAN ID attribute. Mikrotik uses own attributes for VLAN assignment.');
echo gettext('Set the Mikrotik VLAN type attribute. For general use a value of 0 is fine.');
echo gettext('Set the SSL version to use. In AUTO mode, only TLS is used.');
echo gettext('Set the Service-Type attributes for this user.');
echo gettext('Set the certificate to use for HTTPS connections.');
echo gettext('Set the default EAP type.');
echo gettext('Set the destination IP or network to match. Leave this field empty for using "any".');
echo gettext('Set the filter to search for users, for Active Directory change uid to samaccountname.');
echo gettext('Set the gateway IP for this pool. It will be the gateway for the clients and also used as the identifier.');
echo gettext('Set the gateway IP here when using Disable Routes feature. You also have to add this as a gateway in OPNsense.');
echo gettext('Set the hostname or IP address to connect to.');
echo gettext('Set the interface MTU for this interface. Leaving empty uses the MTU from main interface which is fine for most setups.');
echo gettext('Set the interface specific DNS server.');
echo gettext('Set the maximum download bandwith for ChilliSpot attribute. The value is treated as kbits/s.');
echo gettext('Set the maximum download bandwith for WISPr attribute. The value is treated as bits/s.');
echo gettext('Set the maximum object size (default 4MB when left empty).');
echo gettext('Set the maximum object size in memory (default 512KB when left empty).');
echo gettext('Set the maximum session limit in seconds. This can be used by the Captive Portal.');
echo gettext('Set the maximum upload bandwith for ChilliSpot attribute. The value is treated as kbits/s.');
echo gettext('Set the maximum upload bandwith for WISPr attribute. The value is treated as bits/s.');
echo gettext('Set the minimum download bandwith for WISPr attribute. The value is treated as bits/s.');
echo gettext('Set the minimum upload bandwith for WISPr attribute. The value is treated as bits/s.');
echo gettext('Set the name for this AVPair');
echo gettext('Set the name for this instance.');
echo gettext('Set the name for this signatures.');
echo gettext('Set the password for the user. Allowed characters are 0-9, a-z, A-Z, and ,._-!$%/()+#= with up to 128 characters.');
echo gettext('Set the password of remote MySQL server.');
echo gettext('Set the port of remote MySQL server.');
echo gettext('Set the port to connect');
echo gettext('Set the protocol to use.');
echo gettext('Set the service poll time. Either as a number of cycles "<i>NUMBER</i> CYCLES" or Cron-style "* 8-19 * * 1-5"');
echo gettext('Set the shared secret for the client. Must match on both sides.');
echo gettext('Set the source IP or network to match. Leave this field empty for using "any".');
echo gettext('Set the subnet mask for this pool.');
echo gettext('Set the unique username for the user. Allowed characters are 0-9, a-z, A-Z, and ._-@/');
echo gettext('Set the user of remote MySQL server.');
echo gettext('Set the value for this AVPair.');
echo gettext('Set this option to disable this static route without removing it from the list.');
echo gettext('Set this option to enable this destination.');
echo gettext('Set where to log radius requests, defaults to file.');
echo gettext('Sets auth-nocache in the exported configuration when password authentication is used. This prevents OpenVPN from caching passwords in memory.');
echo gettext('Sets the DNS resolution mode.');
echo gettext('Shared Secret');
echo gettext('Shared secret (PSK) for this peer. You can generate a key using "wg genpsk" on a client with WireGuard installed.');
echo gettext('Signature Id');
echo gettext('Simply <i>alert</i> or <i>restart</i> the service or <i>execute</i> a program.');
echo gettext('Simultaneous-Use');
echo gettext('Slow Transactions');
echo gettext('Some filtering categories such as "porn" are containing millions of records and require your device to have a minimum of 8GB of RAM and a 4 cores processor with 1.5GHz or more - loading selected zones in memory can take minutes.');
echo gettext('Source');
echo gettext('Source / Invert');
echo gettext('Source IP');
echo gettext('Source address');
echo gettext('Source port');
echo gettext('Source port number or well known name (imap, imaps, http, https, ...), for ranges use a dash');
echo gettext('Specifies the maximum size of packets to match in bytes');
echo gettext('Specifies the size of the hash table used for storing the various dynamic pipes configured with the mask setting');
echo gettext('Specifies the size of the hash table used for storing the various dynamic queues configured with the mask setting');
echo gettext('Specify the scheduling algorithm to use');
echo gettext('Split long running flows into smaller parts.');
echo gettext('Src-port');
echo gettext('Start');
echo gettext('Start Delay');
echo gettext('Start TLS');
echo gettext('Start send percentage data');
echo gettext('Start servers');
echo gettext('Start the Monit httpd service.');
echo gettext('State File');
echo gettext('Stop');
echo gettext('Strict QNAME Minimisation');
echo gettext('Subnet to receive, e.g. 255.255.255.0');
echo gettext('Subnetmask');
echo gettext('Suppress Squid version string info in HTTP headers and HTML error pages.');
echo gettext('Suppress version string');
echo gettext('Syslog Facility');
echo gettext('TCP Listen Port');
echo gettext('TCP port');
echo gettext('TCP/IP Version');
echo gettext('TLS Minimum Version');
echo gettext('TTL for Expired Responses');
echo gettext('TTL for Host Cache entries');
echo gettext('Tag Queries and Replies');
echo gettext('Target');
echo gettext('Tests');
echo gettext('The Administrator of this server. Used when displaying information about this server.');
echo gettext('The Interface for \'Network\' checks.');
echo gettext('The M/Monit URL.<br><i>https://user:pass@192.168.1.10:8443/collector</i><br>If you want to control Monit services from your M/Monit instance you have to configure the Monit Port too and add corresponding firewall rules as well.');
echo gettext('The PID file of the process.');
echo gettext('The Packet length is the number of bytes of each packet that will be captured. Default value is 0, which will capture the entire frame regardless of its size.');
echo gettext('The SSL fingerprint, for example "B5:E1:B3:70:5E:7C:FF:EB:92:C4:29:E5:5B:AC:2F:AE:70:17:E9:9E".');
echo gettext('The commands here will be disabled and cannot be used anymore.');
echo gettext('The detection engine builds internal groups of signatures. The engine allow us to specify the profile to use for them, to manage memory on an efficient way keeping a good performance.');
echo gettext('The email address to send alerts to.');
echo gettext('The email format for alerts.<br><i>Subject: $SERVICE on $HOST failed</i>');
echo gettext('The hard size limit of all queues managed by this instance, leave empty for defaults');
echo gettext('The header which should be used to send the username to the ICAP server.');
echo gettext('The initial number of server processes. Each server process generates a number of threads, which serve the requests.');
echo gettext('The listen port of the Monit httpd service.');
echo gettext('The log file of the Monit process. This can be the keyword <i>syslog</i> or the path to a file.');
echo gettext('The maximum allowed number of server processes.');
echo gettext('The maximum number of requests can be served by one connection');
echo gettext('The maximum number of requests that a child process can serve. After this number has been reached, process dies.');
echo gettext('The maximum size of files which will be scanned by antivirus service. You can use K and M indicators to define size in kilobytes or megabytes.');
echo gettext('The maximum time in seconds waiting for a new request before a connection will be closed.');
echo gettext('The name of the service.');
echo gettext('The name of the test.');
echo gettext('The number of bytes a queue can serve before being moved to the tail of old queues list (bytes), leave empty for defaults');
echo gettext('The number of databases you would like to have.');
echo gettext('The number of eventqueue slots.');
echo gettext('The number of flow queues that are created and managed, leave empty for defaults');
echo gettext('The number of threads per child process.');
echo gettext('The password for access to SNMP agent');
echo gettext('The password for mail server authentication.');
echo gettext('The path to the eventqueue directory.');
echo gettext('The percentage of data that can be sent by the c-icap server before receiving the complete body of a request. This feature in conjuction with the folowing can be useful because if the download of the object takes a lot of time the connection of web client to proxy can be expired.');
echo gettext('The port can be either the source or destination port. The packet capture will look for this port in either field.');
echo gettext('The port number where Squid listens for SNMP requests. To enable SNMP support set this to a suitable port number. Port number 3401 is often used for the Squid SNMP agent.');
echo gettext('The port number where Squid sends and receives ICP queries to and from neighbor caches. Leave blank to disable (default). The standard UDP port for ICP is 3130.');
echo gettext('The port of the mail server. Typically 465 for SSL or 25 for TLS and non secure connections.');
echo gettext('The port the proxy service will listen to.');
echo gettext('The port the ssl proxy service will listen to.');
echo gettext('The prompt will be displayed in the authentication request window.');
echo gettext('The service check type.');
echo gettext('The start script of the service.');
echo gettext('The state file of the Monit process.');
echo gettext('The stop script of the service.');
echo gettext('The target IP address for \'Remote Host\' and \'Network\' checks.');
echo gettext('The test condition. E.g.<br><i>cpu is greater than 50%</i><br><i>failed host 127.0.0.1 port 22 protocol ssh</i><br>');
echo gettext('The time in seconds after which a connection without activity can be cancelled.');
echo gettext('The timeout for custom program checks.');
echo gettext('The total number of authenticator processes to spawn.');
echo gettext('The username for mail server authentication.');
echo gettext('The username:password or host/network etc. for accessing the Monit httpd service.<br>See <a rel="help" target="_blank" href="https://mmonit.com/monit/documentation/monit.html#Authentication">Monit Authentication</a>');
echo gettext('This allows you to bind to an external LDAP server. Be aware that FreeRADIUS will not start if there is no further configuration.');
echo gettext('This allows you to define a fallback VLAN-Group-ID. Warning: Setting this option will send an accepted RADIUS reply even if the authentication attempt fails.');
echo gettext('This allows you to dynamically assign VLANs on your physical switch ports.');
echo gettext('This can help you when having connection issues with IPv6 enabled servers. Set a value in seconds');
echo gettext('This enables CRL checking, please restart this service with every change to the CRL.');
echo gettext('This enables LDAP authentication in inner-tunnel configuration. This is needed for protocols requiring encrypted authentication like 802.1X.');
echo gettext('This enables SQLite module and accounting.');
echo gettext('This enables remote MySQL support.');
echo gettext('This enables the ChilliSpot attributes assignment via users tab.');
echo gettext('This enables the EXOS VLAN and policy attributes assignment via users tab.');
echo gettext('This enables the Max-Daily-Session attribute assignment via users tab.');
echo gettext('This enables the Mikrotik attributes assignment via users tab.');
echo gettext('This enables the WISPr attributes assignment via users tab.');
echo gettext('This is a list with service tests.');
echo gettext('This is the email address displayed in error messages to the users.');
echo gettext('This is the hostname to be displayed in proxy server error messages.');
echo gettext('This is the instance number to give the wg interface a unique name (wgX).');
echo gettext('This option allows you to disable the caching feature of the engine.');
echo gettext('This option enables scanning of HWP3 files.');
echo gettext('This option enables scanning of OLE2 files, such as Microsoft Office documents and .msi files.');
echo gettext('This option enables scanning within PDF files.');
echo gettext('This option enables scanning within SWF files.');
echo gettext('This option enables scanning xml-based document files supported by libclamav.');
echo gettext('This option reverses the order of preference to make Squid contact dual-stack websites over IPv4 first. Squid will still perform both IPv6 and IPv4 DNS lookups before connecting. This option will restrict the situations under which IPv6 connectivity is used (and tested) and will hide network problems which would otherwise be detected and warned about.');
echo gettext('This option sets the maximum amount of data to be scanned for each input file. Archives and other containers are recursively extracted and scanned up to this value.');
echo gettext('This specifies for how long (in hours) the proxy server assumes an externally validated username and password combination is valid (Time To Live). When the TTL expires, the user will be prompted for credentials again.');
echo gettext('This will activate ClamAV');
echo gettext('This will activate WireGuard and start all enabled instances.');
echo gettext('This will activate certificate based authentication (EAP-TLS) and validation (EAP-TTLS). Please choose CA and Certificate below and do not forget to roll out certificates to the clients. If you do not enable this, default installation certificate will be used.');
echo gettext('This will activate inline mode (IPS).');
echo gettext('This will activate nProbe.');
echo gettext('This will activate ntopng.');
echo gettext('This will activate the DHCP FreeRADIUS service.');
echo gettext('This will activate the FreeRADIUS DHCP service.');
echo gettext('This will activate the FreeRADIUS service.');
echo gettext('This will activate the Zerotier service');
echo gettext('This will activate the c-icap service.');
echo gettext('This will activate the clamd service.');
echo gettext('This will activate the freshclam service.');
echo gettext('This will activate the static DHCP lease.');
echo gettext('This will allow to take settings user name from local squid');
echo gettext('This will enable TCP port 3310 in addition to the local socket.');
echo gettext('This will enable logging of access log.');
echo gettext('This will enable or disable the AVPair.');
echo gettext('This will enable or disable the client config.');
echo gettext('This will enable or disable the list.');
echo gettext('This will enable or disable the server config.');
echo gettext('This will enable or disable the user account.');
echo gettext('This will let nProbe connect to ntopng, as opposite to ntopng connecting to nProbe (useful in presence of NAT or firewall).');
echo gettext('This will let nProbe receive IPS policies automatically through ZMQ events from ntopng. If this option is enabled then the below policies will be ignored');
echo gettext('This will make the captive portal always send accounting requests, rather than just when there is a need for accounting (e.g. when there is a daily session limit).');
echo gettext('This will prevent installing routes. Usually you only enable this to do own routing decisions via a local gateway and gateway rules.');
echo gettext('This will run ntopng in Community mode, a license is not required in this mode.');
echo gettext('Threads per child');
echo gettext('Timeout');
echo gettext('Timeout in seconds when connecting to database server.');
echo gettext('To Day');
echo gettext('To Month');
echo gettext('ToClient');
echo gettext('ToServer');
echo gettext('Toggles the Squid pinger service. This service is used in the selection of the best parent proxy.');
echo gettext('Total bandwidth for this pipe');
echo gettext('Total number of entries in downloaded set.');
echo gettext('Total number of ranges');
echo gettext('Total number of signatures');
echo gettext('Traffic Management Settings');
echo gettext('Translation / target');
echo gettext('Translation port');
echo gettext('Transparent proxy (HTTP)');
echo gettext('Transparent proxy (HTTPS)');
echo gettext('Transport');
echo gettext('Transport certificate to use, please make sure to check the general system log when experiencing issues.
      Error messages can be a bit cryptic from time to time, in which case <a href="https://support.oneidentity.com/kb/263658/common-issues-of-tls-encrypted-message-transfer">this</a> is a good
      resource for tracking common issues.
    ');
echo gettext('Transport protocol');
echo gettext('Tunnel Address');
echo gettext('Type');
echo gettext('Type IP addresses (ex. 192.168.1.100)');
echo gettext('Type IP addresses you want to allow access to the proxy server.');
echo gettext('Type IP addresses you want to deny access to the proxy server.');
echo gettext('Type IP addresses, followed by Enter or comma.');
echo gettext('Type IPs of alternative DNS servers you like to use.');
echo gettext('Type of DNSBL');
echo gettext('Type of resource record, e.g. A or AAAA for IPv4 or IPv6 addresses');
echo gettext('Type or select destinations.');
echo gettext('Type or select interface (Leave blank to disable ftp proxy).');
echo gettext('Type or select interface.');
echo gettext('Type port number or range.');
echo gettext('Type subnet addresses (ex. 192.168.2.0/24)');
echo gettext('Type subnets you want to allow access to the proxy server.');
echo gettext('Type subnets/addresses you want to ignore for the access.log.');
echo gettext('URL');
echo gettext('URL Pattern');
echo gettext('URL of the signature database.');
echo gettext('URLs of Blocklists');
echo gettext('Unrestricted IP addresses');
echo gettext('Unwanted Reply Threshold');
echo gettext('Url');
echo gettext('Use System Nameservers');
echo gettext('Use Via header');
echo gettext('Use a password to protect the pkcs12 file contents');
echo gettext('Use a random local source port (lport) for traffic from the client. Without this set, two clients may not run concurrently.');
echo gettext('Use alternate DNS-servers');
echo gettext('Use c-icap with local squid');
echo gettext('Use custom template package for user login');
echo gettext('Use own certificates');
echo gettext('Use random local port');
echo gettext('Use rfc5424 formated messages for this destination.');
echo gettext('Use the DNS response code NXDOMAIN instead of a destination address.');
echo gettext('Use this option if your usernames need to be encoded.');
echo gettext('Use this option to invert the sense of the match.');
echo gettext('User Filter');
echo gettext('User error pages');
echo gettext('Username');
echo gettext('Username Header');
echo gettext('Username to bind to LDAP, same format as in Base DN.');
echo gettext('Usual operators here are = or +=');
echo gettext('VLAN ID');
echo gettext('VLAN ID the user receives, e.g. for 802.1X. Leave empty if you don\'t know what it is.');
echo gettext('VLAN priority');
echo gettext('VLAN tag');
echo gettext('VNI');
echo gettext('VXLAN Network Identifier (VNI) that identifies the virtual network segment membership of the interface.');
echo gettext('Validate server subject');
echo gettext('Value');
echo gettext('Verify CN');
echo gettext('Verify SSL certificates');
echo gettext('Verify the server certificate name when the client connects');
echo gettext('Version');
echo gettext('Visible Hostname');
echo gettext('WAN interfaces');
echo gettext('WISPr Bandwith Max DOWN');
echo gettext('WISPr Bandwith Max UP');
echo gettext('WISPr Bandwith Min DOWN');
echo gettext('WISPr Bandwith Min UP');
echo gettext('Waiting for a new job will timeout after this time in seconds.');
echo gettext('Weight');
echo gettext('Weight of this queue (1..100), used to prioritize within a pipe. (1 is low, 100 is high)');
echo gettext('When enabled the subnets of the selected interfaces will be added to the allow access list.');
echo gettext('When set, the system will capture all traffic present on the interface in stead of the traffic heading to the firewall.');
echo gettext('Whitelist');
echo gettext('Whitelist Domains');
echo gettext('Whitelist destination domains. You may use a regular expression, use a comma or press Enter for new item. Examples: "mydomain.com" matches on "*.mydomain.com"; "^https?:\/\/([a-zA-Z]+)\.mydomain\." matches on "http(s)://textONLY.mydomain.*"; "\.gif$" matches on "\*.gif" but not on "\*.gif\test"; "\[0-9]+\.gif$" matches on "\123.gif" but not on "\test.gif"');
echo gettext('Whitelisted domain.');
echo gettext('Whitespace handling of URI');
echo gettext('Windows Certificate System Store');
echo gettext('With this option clamav will try to detect broken executables (both PE and ELF) and mark them as Broken.');
echo gettext('With this option enabled OLE2 files with VBA macros, which were not detected by signatures will be marked as "Heuristics.OLE2.ContainsMacros".');
echo gettext('With this option you can set a time frame how long the user is allowed to be logged in.');
echo gettext('With this option, you can set the size of the packets on your network. It is possible that bigger packets have to be processed sometimes. The engine can still process these bigger packets, but processing it will lower the performance.');
echo gettext('X-Forwarded-For header handling');
echo gettext('You may enter a description here for your reference (not parsed)');
echo gettext('You may enter a description here for your reference (not parsed).');
echo gettext('YouTube Filter');
echo gettext('ZMQ Endpoint');
echo gettext('ZMQ Endpoint for receiving IPS policies updates published by ntopng.');
echo gettext('ZMQ Endpoint this service will send flows to.');
echo gettext('ZMQ Probe Mode');
echo gettext('Zerotier Network ID e.g., 161411d4f6abe4a7');
echo gettext('Zone number');
echo gettext('__template__label__');
echo gettext('bytecode');
echo gettext('categories (if available)');
echo gettext('connected pipe for this queue');
echo gettext('daily');
echo gettext('database.clamav.net is a round-robin record which points to the most reliable mirrors. DO NOT TOUCH the following line unless you know what you are doing.');
echo gettext('default packet size');
echo gettext('destination ip or network, examples 10.0.0.0/24, 10.0.0.1');
echo gettext('deviceId');
echo gettext('enable this rule');
echo gettext('enabled');
echo gettext('invert destination (not)');
echo gettext('invert port (not)');
echo gettext('invert protocol (not)');
echo gettext('invert source (not)');
echo gettext('local.conf settings');
echo gettext('main');
echo gettext('mask');
echo gettext('matches incoming or outgoing packets or both (default)');
echo gettext('metadata rules per category');
echo gettext('number of dynamic queues, leave empty for default');
echo gettext('order in which the rule will be evaluated (lowest first)');
echo gettext('password (optional)');
echo gettext('pick a color to use.');
echo gettext('rfc5424');
echo gettext('rulesets this policy applies to (all when none selected)');
echo gettext('secondary interface, matches packets traveling to/from interface (1) to/from interface (2). can be combined with direction.');
echo gettext('select categories to use, leave empty for all. Categories are visible after initial download.');
echo gettext('source ip or network, examples 10.0.0.0/24, 10.0.0.1');
echo gettext('ssl ignore cert');
echo gettext('target pipe or queue');
echo gettext('user:password, @group... Finish with TAB.');
echo gettext('username (optional)');
